### ISSUE TITLE
A few bugs with the zoom functionality

### ISSUE THREAD

**Issue by benlogan** [benlogan1981/MarvelMovies#6]
Seems to intermittently lose the connecting lines and doesn't always work without changing your selections. It also changes the location of the nodes on the screen - it needs to re-center the view to keep the node under focus at the center of the screen.

**Comment by satyashani** [comment]
Intermittent losing connection - Do the edges vanish completely during zoom? The node hover function is active during zoom, so whichever node comes under the mouse while zooming becomes active and its network is focused and other nodes and edges become slightly transparent.
Doesn't always work - zoom can only work when force layout has 'cooled'. I wanted to add an icon that reflects that zoom is active/inactive.
Changing location of nodes - zoom actually doesn't act with respect to center of graph but the location of mouse pointer so that user can zoom on a specific node. Rest of the graph is accordingly moved. To recenter the displaced graph, drag has been added. Should it zoom with respect to center of graph?

**Comment by benlogan** [comment]
Zoom is just generally very buggy. Doesn't always work at all. I guess this is what you mean by the layout 'cooling'. That shouldn't be necessary - is that a limitation of our implementation. Even right at the start, without any interaction (I have clicked to give the canvas focus).

As a quick debug method to help us understand what is going on, definitely add an indicator that tells us when you can and can't zoom.

Don't bother changing the centre of the zoom yet, until we've got the main zoom problems sorted - it may be fine. It's much more of a problem when you've searched for a movie, rather than when you are viewing the full graph.

Search for 'xmen'. Once it's cooled, zoom works ok (apart from the centre issue). The edges are fine. It's difficult to work out when or why the edges become transparent. Can you explain this logic, we should remove this, or are you saying it's a bug/feature? OK, I've just had another go - the edges appear to completely disappear when zoomed in and hovered over the active node. I can see the problem - it thinks I'm hovered over a different node.

![image](https://cloud.githubusercontent.com/assets/1737958/6810674/63b1e25e-d25a-11e4-823d-29bb510560ed.png)

Here my mouse is over the main centre node (xmen). So this is very closely related to the other bug about force layout on zoom and overlapping nodes. There is node corruption here - this definitely needs fixing or we will have to disable zoom.

**Comment by satyashani** [comment]
This is certainly a bug. The logic for force layout and zoom is when first the nodes are laid out using force algo, which assigns them coordinates. When layout is complete (called cooled due to similarity with particles in a thermodynamic cooling process), then zoom can manipulate positions without affecting result of force layout. This bug appears because when individual nodes are dragged(not the whole graph) force layout tries to rearrange them but under zoom positions are changed. Basically force layout must act only under no-zoom, and zoom must be active only when layout is complete.

I will try a different approach of layout/zoom so that these can work together, if that doesn't work, we'll have to stick with mutually exclusive zoom and layout.
